### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by blue193** [webcat12345/react-admin#1]
Thanks for your project.
It'll be good for me to learn MERN by myself.
How's your work going? It's been a long time since we had separated last year.
Please say hello to your friends from me.
Have a nice day!~hj

**Comment by webcat12345** [comment]
It's glad to see you again. Sure, I will send your regards to here.
Always have faith in your ability; success will come your way eventually. Best of luck!

**Comment by blue193** [comment]
Hello, webcat~

I have a question.
I heard that some of my friends will soon come back to here.
so, I'd love to learn the fact if sure or not.
Thanks.

**Comment by blue193** [comment]
I'm waiting for your reply.
Thanks
